
CREATE DATABASE tata_supply_chain;
USE tata_supply_chain;

CREATE TABLE PART_CATEGORY(
 CategoryID INT PRIMARY KEY AUTO_INCREMENT,
 CategoryName VARCHAR(100) NOT NULL
);

CREATE TABLE PARTS(
 PartNo INT PRIMARY KEY,
 CategoryID INT NOT NULL,
 Description VARCHAR(255),
 UnitOfMeasure VARCHAR(20),
 UnitRate DECIMAL(10,2),
 OpeningStock INT DEFAULT 0,
 MinimumStock INT,
 OrderQuantity INT,
 FOREIGN KEY(CategoryID) REFERENCES PART_CATEGORY(CategoryID)
);

CREATE TABLE VENDOR(
 VendorCode INT PRIMARY KEY,
 VendorName VARCHAR(100),
 VendorAddress VARCHAR(255),
 PaymentTerms VARCHAR(100)
);

CREATE TABLE VENDOR_PART(
 VendorCode INT,
 PartNo INT,
 SupplyRate DECIMAL(10,2),
 PRIMARY KEY(VendorCode,PartNo),
 FOREIGN KEY(VendorCode) REFERENCES VENDOR(VendorCode),
 FOREIGN KEY(PartNo) REFERENCES PARTS(PartNo)
);

CREATE TABLE TRANSPORTER(
 TransporterID INT PRIMARY KEY,
 TransporterName VARCHAR(100)
);

CREATE TABLE PURCHASE_ORDER(
 PONo INT PRIMARY KEY,
 VendorCode INT,
 OrderDate DATE,
 FOREIGN KEY(VendorCode) REFERENCES VENDOR(VendorCode)
);

CREATE TABLE CHALLAN(
 ChallanNo INT PRIMARY KEY,
 ChallanDate DATE,
 PONo INT,
 VendorCode INT,
 TransporterID INT,
 FOREIGN KEY(PONo) REFERENCES PURCHASE_ORDER(PONo),
 FOREIGN KEY(VendorCode) REFERENCES VENDOR(VendorCode),
 FOREIGN KEY(TransporterID) REFERENCES TRANSPORTER(TransporterID)
);

CREATE TABLE GRR(
 GRRNo INT AUTO_INCREMENT PRIMARY KEY,
 ChallanNo INT UNIQUE,
 GeneratedDate DATE,
 Remarks VARCHAR(255),
 FOREIGN KEY(ChallanNo) REFERENCES CHALLAN(ChallanNo)
);

CREATE TABLE GRR_DETAILS(
 GRRNo INT,
 PartNo INT,
 ChallanQty INT,
 PRIMARY KEY(GRRNo,PartNo),
 FOREIGN KEY(GRRNo) REFERENCES GRR(GRRNo),
 FOREIGN KEY(PartNo) REFERENCES PARTS(PartNo)
);

CREATE TABLE QUALITY_INSPECTION(
 InspectionID INT PRIMARY KEY,
 GRRNo INT,
 PartNo INT,
 AcceptedQty INT,
 RejectedQty INT,
 Status VARCHAR(20),
 FOREIGN KEY(GRRNo) REFERENCES GRR(GRRNo),
 FOREIGN KEY(PartNo) REFERENCES PARTS(PartNo)
);

CREATE TABLE MIR(
 MIRNo INT PRIMARY KEY,
 MIRDate DATE
);

CREATE TABLE MIR_DETAILS(
 MIRNo INT,
 PartNo INT,
 QtyIssued INT,
 PRIMARY KEY(MIRNo,PartNo),
 FOREIGN KEY(MIRNo) REFERENCES MIR(MIRNo),
 FOREIGN KEY(PartNo) REFERENCES PARTS(PartNo)
);
